In [49]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np 
%matplotlib inline

In [50]:
df = pd.read_csv('data/csvs/examenes.csv')
#df = df.sample(n = 100, replace = False)

In [51]:
df.head()

,student_id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,1,17,male,diploma,2.78,92.9,yes,7.4,poor,coaching,low,hard,58.9
1,2,23,other,bca,3.37,64.8,yes,4.6,average,online videos,medium,moderate,54.8
2,3,22,male,b.sc,7.88,76.8,yes,8.5,poor,coaching,high,moderate,90.3
3,4,20,other,diploma,0.67,48.4,yes,5.8,average,online videos,low,moderate,29.7
4,5,20,female,diploma,0.89,71.6,yes,9.8,poor,coaching,low,moderate,43.7

# Prueba ANOVA (C vs N)

In [52]:
# 1. generar una lista que contenga las listas de los grupos que queremos comparar
grupos = []
for grupo in df["study_method"].unique():
    filtro = df["study_method"] == grupo
    grupo_act = df[filtro]
    grupos.append(list(grupo_act["exam_score"]))

In [53]:
from scipy.stats import f_oneway

f_stat, p_value_anova = f_oneway(*grupos)

if p_value_anova < 0.05:
    print("Se rechaza H0: Los metodos de estudio impactan en el examen score")
else:
    print("No se rechaza H0: Los metodos de estudio NO impactan en el examen score")

Se rechaza H0: Los metodos de estudio impactan en el examen score

# Prueba Chi cuadrada (C vs C)

¿Existe asociación entre el genero y el acceso a internet?

$H_0 :$ El género y el acceso a internet son independientes / No exsite asociación entre el genero y el acceso a internet

$H_a :$ El género y el acceso a internet no son independientes / Existe asociación entre el género y el acceso a internet

In [54]:
# 1. Obtener la tabla de contingencias
tabla_contingencias = pd.crosstab(df["gender"], df["study_method"])
tabla_contingencias

study_method  coaching  group study  mixed  online videos  self-study
gender
female            1350         1273   1284           1323        1349
male              1315         1282   1324           1386        1388
other             1371         1367   1286           1360        1342

In [55]:
from scipy.stats import chi2_contingency

chi2_stat, p_value_chi2, _, _ = chi2_contingency(tabla_contingencias)
if p_value_chi2 < 0.05:
    print("Se rechaza H0: Existe asociación entre el genero y el acceso a internet")
else:
    print("No se rechaza H0: NO Existe asociación entre el genero y el acceso a internet")

No se rechaza H0: NO Existe asociación entre el genero y el acceso a internet